### ISSUE TITLE
Where to look for more control over the http request for fonts?

### ISSUE THREAD

**Issue by toranb** [lfridael/ember-cli-font-awesome#33]
Currently when this addon is installed I see an http request for ...

http://foobar.com/fonts/fontawesome-webfont.woff2?v=4.3.0

If instead I wanted to nest fonts under the assets directory ... is this configurable? If not ... what can I modify manually to get this instead?

http://foobar.com/assets/fonts/fontawesome-webfont.woff2?v=4.3.0

**Comment by lfridael** [comment]
The font path is referred to by the Font Awesome CSS and is not directly configurable.

One way to change the asset path is to include the original Font Awesome LESS (or SASS) instead of the prebuilt CSS. There's a variable to control the font path. See https://github.com/FortAwesome/Font-Awesome/blob/master/less/variables.less

**Comment by toranb** [comment]
Excellent ! thanks for the quick reply!
